# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: nosql-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: shop
    ports:
      - "27017:27017"
    cap_add:
      - SYS_NICE
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user123
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://user123:pass123@mongo:27017/
